<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <OutputPath Condition="'$(Configuration)'=='Debug'">..\bin\debug\</OutputPath>
    <GenerateDocumentationFile Condition="'$(Configuration)'=='Release'">true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenSourceToolkit.Core\OpenSourceToolkit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FIGLet" Version="2.0.14" />
    <PackageReference Include="SkiaSharp" Version="4.150.1" />
  </ItemGroup>

</Project>
