<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <OutputPath Condition="'$(Configuration)'=='Debug'">..\bin\debug\</OutputPath>

    <Authors>OpenSourceToolkit Contributors</Authors>
    <Company>OpenSourceToolkit</Company>
    <Product>OpenSourceToolkit.Net</Product>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile Condition="'$(Configuration)'=='Release'">true</GenerateDocumentationFile>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="10.0.8" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>

</Project>
