<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OpenSourceToolkit.Core\OpenSourceToolkit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.15.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260602" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260602" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.9" />
    <PackageReference Include="System.Text.Json" Version="10.0.9" />
    <PackageReference Include="YamlDotNet" Version="18.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <OutputPath Condition="'$(Configuration)'=='Debug'">..\bin\debug\</OutputPath>
    <Authors>OpenSourceToolkit Contributors</Authors>
    <Company>OpenSourceToolkit</Company>
    <Product>OpenSourceToolkit.Net</Product>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile Condition="'$(Configuration)'=='Release'">true</GenerateDocumentationFile>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
